services:
  - type: web
    name: redxpma-api
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install --include=dev
    startCommand: npm run start:api
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          type: web
          name: redxpma-web
          envVarKey: RENDER_EXTERNAL_URL
      - key: CLIENT_URLS
        fromService:
          type: web
          name: redxpma-web
          envVarKey: RENDER_EXTERNAL_URL
      - key: GOOGLE_CLIENT_ID
        sync: false

  - type: web
    name: redxpma-web
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install --include=dev && npm run build:web
    startCommand: npm run start:web
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: redxpma-web
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: redxpma-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        sync: false
